config_version = "1"

[[components]]
pkg = "cargo"
target = "x86_64-pc-windows-msvc"

[[components]]
pkg = "clippy-preview"
target = "x86_64-pc-windows-msvc"

[[components]]
pkg = "rust-docs"
target = "x86_64-pc-windows-msvc"

[[components]]
pkg = "rust-std"
target = "x86_64-pc-windows-msvc"

[[components]]
pkg = "rustc"
target = "x86_64-pc-windows-msvc"

[[components]]
pkg = "rustfmt-preview"
target = "x86_64-pc-windows-msvc"
